[package]
name = "categories"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
graphs = { path = "crates/graphs" }
force_graph = { path = "crates/force_graph" }
geng = "0.8.0"